admin_healthyinfo_content:
  path: healthyinfocheckout/content
  methods: [GET, POST]
  defaults:
    _controller: PrestaShop\Module\HealthyInfoCheckout\Controller\AdminHealthyInfoController::initContent

admin_healthinfo_content_delete:
  path: healthyinfocheckout/content/delete/{id}
  methods: [GET]
  defaults:
    _controller: PrestaShop\Module\HealthyInfoCheckout\Controller\AdminHealthyInfoController::deleteContent

admin_healthinfo_list:
  path: healthyinfocheckout/list
  methods: [GET]
  defaults:
    _controller: PrestaShop\Module\HealthyInfoCheckout\Controller\AdminHealthyInfoController::listContent

admin_healthinfo_list_update:
  path: healthyinfocheckout/list/update/{id}
  methods: [POST]
  defaults:
    _controller: PrestaShop\Module\HealthyInfoCheckout\Controller\AdminHealthyInfoController::updateHealthyInfoList

admin_healthinfo_list_update_form:
  path: healthyinfocheckout/list/update/{id}/form
  methods: [GET, POST]
  defaults:
    _controller: PrestaShop\Module\HealthyInfoCheckout\Controller\AdminHealthyInfoController::showUpdateForm

