admin_healthy_content:
  path: healthyinfocheckout/content
  methods: [GET, POST]
  defaults:
    _controller: PrestaShop\Module\healthyinfocheckout\Controllers\AdminHealthyInfoController::initContent
