admin_healthy_question:
  path: healthyQuestion/select
  methods: [GET, POST]
  defaults:
    _controller: PrestaShop\Module\HealthyInfoCheckOut\Controllers\HealthyInfoCheckOutActionsModuleFrontController::processSelect
    _legacy_controller: false
    _syilex: false
    _validate: false
    _admin: true
    _is_module_controller: true
    _legacy_link: false
    _legacy_link_only: false
