admin_healthyinfo_content:
  path: healthyinfocheckout/content
  methods: [GET, POST]
  defaults:
    _controller: PrestaShop\Module\HealthyInfoCheckout\Controller\AdminHealthyInfoController::initContent
